server {
    listen 80;
    server_name sgm.mabcontrol.ar;

    location / {
        proxy_pass http://localhost:5051; # Cambia este puerto si tu backend escucha en otro
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Aumentar límite de subida para fotos de productos y restauraciones de BD
    client_max_body_size 100M;
}
